openapi: 3.0.0
info:
  title: Pet Store Service
  description: This is a sample server Petstore server.
  version: v1
tags: []
paths:
  /pets:
    get:
      operationId: Pets_list
      parameters:
        - name: skip
          in: query
          required: true
          schema:
            type: integer
            format: int32
        - name: top
          in: query
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
    post:
      operationId: Pets_create
      parameters: []
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
  /pets/{petId}:
    get:
      operationId: Pets_read
      parameters:
        - name: petId
          in: path
          required: true
          schema:
            type: integer
            format: int32
        - name: if-match
          in: header
          required: false
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          headers:
            e-tag:
              required: true
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        '404':
          description: The server cannot find the requested resource.
  /pets/{petId}/toys:
    get:
      operationId: PetToys_list
      parameters:
        - name: petId
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PetToys.Toy'
  /tenants/{tenantId}/users/{userName}:
    get:
      operationId: UserOperations_getUser
      parameters:
        - $ref: '#/components/parameters/CommonParameters.tenantId'
        - $ref: '#/components/parameters/CommonParameters.userName'
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      operationId: UserOperations_updateUser
      parameters:
        - $ref: '#/components/parameters/CommonParameters.tenantId'
        - $ref: '#/components/parameters/CommonParameters.userName'
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  $ref: '#/components/schemas/User'
              required:
                - user
components:
  parameters:
    CommonParameters.tenantId:
      name: tenantId
      in: path
      required: true
      schema:
        type: string
    CommonParameters.userName:
      name: userName
      in: path
      required: true
      schema:
        type: string
  schemas:
    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
    Pet:
      type: object
      required:
        - name
        - age
        - kind
      properties:
        name:
          type: string
          minLength: 100
        age:
          type: integer
          format: int32
          minimum: 0
          maximum: 100
        kind:
          type: string
          enum:
            - dog
            - cat
            - fish
    PetToys.Toy:
      type: object
      required:
        - name
      properties:
        name:
          type: string
    User:
      type: object
      required:
        - name
      properties:
        name:
          type: string
    Versions:
      type: string
      enum:
        - v1
servers:
  - url: '{url}'
    description: Single server endpoint
    variables:
      url:
        default: https://petstore.swagger.io
